name: CI

on:
  push:
    branches: ["main", "develop", "feature/**", "bugfix/**", "release/**"]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install black ruff

      - name: Run Ruff
        run: ruff check .

      - name: Run tests
        run: pytest -q

      - name: Check formatting with Black
        run: black --check .
